import { readdir, rm } from "fs/promises";
import { join } from "path";

interface FileEntry {
  urlPath: string;
  filePath: string;
}

async function collectFiles(
  dir: string,
  base = ""
): Promise<FileEntry[]> {
  const entries: FileEntry[] = [];
  const items = await readdir(dir, { withFileTypes: true });

  for (const item of items) {
    const filePath = join(dir, item.name);
    const urlPath = `${base}/${item.name}`;

    if (item.isDirectory()) {
      entries.push(...(await collectFiles(filePath, urlPath)));
    } else {
      entries.push({ urlPath, filePath });
    }
  }
  return entries;
}

async function build() {
  const startTime = Date.now();

  // Clean previous build artifacts
  console.log("Cleaning previous build...");
  await rm("./dist", { recursive: true, force: true });
  await rm("./dist-manifest.ts", { force: true });

  // Build the Vite app
  console.log("Building Vite app...");
  const viteBuild = Bun.spawn(["bun", "run", "vite", "build"], {
    stdout: "inherit",
    stderr: "inherit",
  });
  await viteBuild.exited;

  if (viteBuild.exitCode !== 0) {
    console.error("Vite build failed");
    process.exit(1);
  }

  // Collect all files from dist
  console.log("Generating asset manifest...");
  const files = await collectFiles("./dist");

  // Generate import statements
  const imports: string[] = [];
  const assetEntries: string[] = [];

  let indexHtmlVar = "";

  files.forEach((file, index) => {
    const varName = `f${index}`;
    imports.push(
      `import ${varName} from "./${file.filePath}" with { type: "file" };`
    );

    if (file.urlPath === "/index.html") {
      indexHtmlVar = varName;
    } else {
      assetEntries.push(`  "${file.urlPath}": ${varName},`);
    }
  });

  // Also map "/" to index.html
  if (indexHtmlVar) {
    assetEntries.push(`  "/": ${indexHtmlVar},`);
  }

  const manifest = `// Auto-generated by build-executable.ts
// Do not edit manually

${imports.join("\n")}

export const assets: Record<string, string> = {
${assetEntries.join("\n")}
};

export const indexHtml = ${indexHtmlVar};
`;

  await Bun.write("./dist-manifest.ts", manifest);

  // Compile to executable
  console.log("Compiling executable...");
  const compile = Bun.spawn(
    ["bun", "build", "--compile", "--minify", "server.ts", "-o", "reader"],
    {
      stdout: "inherit",
      stderr: "inherit",
    }
  );
  await compile.exited;

  if (compile.exitCode !== 0) {
    console.error("Compilation failed");
    process.exit(1);
  }

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);
  console.log(`\nBuild complete in ${elapsed}s`);
  console.log(`   Executable: ./reader`);
  console.log(`   Run with: ./reader`);
  console.log(`   Or with custom port: PORT=8080 ./reader`);
}

build().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
