import { serve, file } from "bun";

// This file is generated by build-executable.ts
import { assets, indexHtml } from "./dist-manifest";

const PORT = parseInt(process.env.PORT || "3000", 10);

// MIME types for common file extensions
const mimeTypes: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
};

function getMimeType(path: string): string {
  const ext = path.substring(path.lastIndexOf("."));
  return mimeTypes[ext] || "application/octet-stream";
}

serve({
  port: PORT,
  fetch(req) {
    const url = new URL(req.url);
    const pathname = url.pathname;

    // Serve static assets
    if (assets[pathname]) {
      return new Response(file(assets[pathname]), {
        headers: {
          "Content-Type": getMimeType(pathname),
          "Cache-Control": pathname.includes("/assets/")
            ? "public, max-age=31536000, immutable"
            : "no-cache",
        },
      });
    }

    // SPA fallback: serve index.html for all non-asset routes
    return new Response(file(indexHtml), {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "no-cache",
      },
    });
  },
});

console.log(`Server running at http://localhost:${PORT}`);
