/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SFeedIdRouteImport } from './routes/s.$feedId'
import { Route as FFolderIdRouteImport } from './routes/f.$folderId'

const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SFeedIdRoute = SFeedIdRouteImport.update({
  id: '/s/$feedId',
  path: '/s/$feedId',
  getParentRoute: () => rootRouteImport,
} as any)
const FFolderIdRoute = FFolderIdRouteImport.update({
  id: '/f/$folderId',
  path: '/f/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/starred': typeof StarredRoute
  '/f/$folderId': typeof FFolderIdRoute
  '/s/$feedId': typeof SFeedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/starred': typeof StarredRoute
  '/f/$folderId': typeof FFolderIdRoute
  '/s/$feedId': typeof SFeedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/starred': typeof StarredRoute
  '/f/$folderId': typeof FFolderIdRoute
  '/s/$feedId': typeof SFeedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage' | '/starred' | '/f/$folderId' | '/s/$feedId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manage' | '/starred' | '/f/$folderId' | '/s/$feedId'
  id: '__root__' | '/' | '/manage' | '/starred' | '/f/$folderId' | '/s/$feedId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRoute: typeof ManageRoute
  StarredRoute: typeof StarredRoute
  FFolderIdRoute: typeof FFolderIdRoute
  SFeedIdRoute: typeof SFeedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$feedId': {
      id: '/s/$feedId'
      path: '/s/$feedId'
      fullPath: '/s/$feedId'
      preLoaderRoute: typeof SFeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$folderId': {
      id: '/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/f/$folderId'
      preLoaderRoute: typeof FFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRoute: ManageRoute,
  StarredRoute: StarredRoute,
  FFolderIdRoute: FFolderIdRoute,
  SFeedIdRoute: SFeedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
