/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'
import { Route as FeedFeedIdRouteImport } from './routes/feed.$feedId'
import { Route as BlogIntroductionRouteImport } from './routes/blog.introduction'
import { Route as BlogHowToUseRouteImport } from './routes/blog.how-to-use'

const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedFeedIdRoute = FeedFeedIdRouteImport.update({
  id: '/feed/$feedId',
  path: '/feed/$feedId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIntroductionRoute = BlogIntroductionRouteImport.update({
  id: '/blog/introduction',
  path: '/blog/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToUseRoute = BlogHowToUseRouteImport.update({
  id: '/blog/how-to-use',
  path: '/blog/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/starred': typeof StarredRoute
  '/blog/how-to-use': typeof BlogHowToUseRoute
  '/blog/introduction': typeof BlogIntroductionRoute
  '/feed/$feedId': typeof FeedFeedIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/starred': typeof StarredRoute
  '/blog/how-to-use': typeof BlogHowToUseRoute
  '/blog/introduction': typeof BlogIntroductionRoute
  '/feed/$feedId': typeof FeedFeedIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage': typeof ManageRoute
  '/starred': typeof StarredRoute
  '/blog/how-to-use': typeof BlogHowToUseRoute
  '/blog/introduction': typeof BlogIntroductionRoute
  '/feed/$feedId': typeof FeedFeedIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/starred'
    | '/blog/how-to-use'
    | '/blog/introduction'
    | '/feed/$feedId'
    | '/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manage'
    | '/starred'
    | '/blog/how-to-use'
    | '/blog/introduction'
    | '/feed/$feedId'
    | '/folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/starred'
    | '/blog/how-to-use'
    | '/blog/introduction'
    | '/feed/$feedId'
    | '/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRoute: typeof ManageRoute
  StarredRoute: typeof StarredRoute
  BlogHowToUseRoute: typeof BlogHowToUseRoute
  BlogIntroductionRoute: typeof BlogIntroductionRoute
  FeedFeedIdRoute: typeof FeedFeedIdRoute
  FolderFolderIdRoute: typeof FolderFolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$feedId': {
      id: '/feed/$feedId'
      path: '/feed/$feedId'
      fullPath: '/feed/$feedId'
      preLoaderRoute: typeof FeedFeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/introduction': {
      id: '/blog/introduction'
      path: '/blog/introduction'
      fullPath: '/blog/introduction'
      preLoaderRoute: typeof BlogIntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-use': {
      id: '/blog/how-to-use'
      path: '/blog/how-to-use'
      fullPath: '/blog/how-to-use'
      preLoaderRoute: typeof BlogHowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRoute: ManageRoute,
  StarredRoute: StarredRoute,
  BlogHowToUseRoute: BlogHowToUseRoute,
  BlogIntroductionRoute: BlogIntroductionRoute,
  FeedFeedIdRoute: FeedFeedIdRoute,
  FolderFolderIdRoute: FolderFolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
